version: "3.8"
services:
  databse:
    container_name: teamlogger_database
    image: mongo:latest
    volumes:
      - ./data:/data
    ports:
      - "270717:270717"

  backend:
    container_name: teamlogger_backend
    build: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on: teamlogger_database

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    depends_on:
      - teamlogger_database

volumes: data